server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: micro1
          uri: http://localhost:8081/
          predicates:
            - Path=/notes1/**
        - id: micro2
          uri: http://localhost:8082/
          predicates:
            - Path=/notes2/**